USE COOK_O_MATIC_BD;

-- Esborrem tot el contingut per tornar a posar-lo
DELETE FROM LINIES_COMANDA;
UPDATE TAULES SET COMANDA_ACTIVA=NULL WHERE 1;
DELETE FROM TAULES;
DELETE FROM COMANDES;
DELETE FROM CAMBRERS;
DELETE FROM LINIES_ESCANDALL;
DELETE FROM PLATS;
DELETE FROM CATEGORIES;
DELETE FROM UNITATS;
DELETE FROM INGREDIENTS;

-- Primer insertem les dades estàtiques
INSERT INTO CATEGORIES VALUES (1,'Entrants','9aed6d');
INSERT INTO CATEGORIES VALUES (2,'Primers','fcbc32');
INSERT INTO CATEGORIES VALUES (3,'Segons','dbd818');
INSERT INTO CATEGORIES VALUES (4,'Postres','de1670');
INSERT INTO CATEGORIES VALUES (5,'Amanides','00ff15');
INSERT INTO CATEGORIES VALUES (6,'Carn','eb4034');
INSERT INTO CATEGORIES VALUES (7,'Peix','170ceb');
INSERT INTO CATEGORIES VALUES (8,'Arrossos','aceb0c');
INSERT INTO CATEGORIES VALUES (9,'Pasta','fcf800');
INSERT INTO CATEGORIES VALUES (10,'Gelats','8d03ff');


-- Insertem els plats, que fan referència a Categories
INSERT INTO PLATS VALUES (1,'Mini-burguers','', 							5.0,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/1.jpg'),		TRUE, 1);
INSERT INTO PLATS VALUES (2,'Crudités de tomàquet, carbassó i ou dur','', 	3.5,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/2.jpg'),		TRUE, 1);
INSERT INTO PLATS VALUES (3,'Ous farcits','', 								6.3,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/3.jpg'),		TRUE, 1);
INSERT INTO PLATS VALUES (4,'Bunyols d''arròs','', 							8.0,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/4.jpg'),		FALSE,1);
INSERT INTO PLATS VALUES (5,'Macarrons','', 								4.0,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/5.jpg'),		TRUE, 2);
INSERT INTO PLATS VALUES (6,'Sopa de carbassó','', 							8.75,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/6.jpg'),	TRUE, 2);
INSERT INTO PLATS VALUES (7,'Sopa gratinada','', 							10.0,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/7.jpg'),	FALSE,2);
INSERT INTO PLATS VALUES (8,'Escalopa amb patates','', 						8.5,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/8.jpg'),		TRUE, 3);
INSERT INTO PLATS VALUES (9,'Pollastre al curry','', 						10.25,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/9.jpg'),	TRUE, 3);
INSERT INTO PLATS VALUES (10,'Combinat de salmó','**Salmó amb cosetes**',	15.55,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/10.jpg'), 	FALSE,3);
INSERT INTO PLATS VALUES (11,'Amanida de pasta','',							7.25,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/11.jpg'), 	TRUE, 5);
INSERT INTO PLATS VALUES (12,'Pastís de llimona','',						6.0,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/12.jpg'), 	FALSE,4);
INSERT INTO PLATS VALUES (13,'Ensaladilla Russa','',						7.5,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/13.jpg'), 	TRUE, 5);
INSERT INTO PLATS VALUES (14,'Macedònia','',								4.75,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/14.jpg'), 	FALSE,4);
INSERT INTO PLATS VALUES (15,'Llonza de porc a la planxa','',				15.75,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/15.jpg'), 	TRUE, 6);
INSERT INTO PLATS VALUES (16,'Pollastre al forn','',						20.25,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/16.jpg'), 	TRUE, 6);
INSERT INTO PLATS VALUES (17,'Pit de pollastre amb la seva salsa','',		12.4,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/17.jpg'), 	TRUE, 6);
INSERT INTO PLATS VALUES (18,'Lligat de porc farcit','',					22.25,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/18.jpg'), 	TRUE, 6);
INSERT INTO PLATS VALUES (19,'Llom de salmó a la planxa','',				12.5,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/19.jpg'), 	TRUE, 7);
INSERT INTO PLATS VALUES (20,'Llom de lluç a la planxa','',					11.25,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/20.jpg'), 	TRUE, 7);
INSERT INTO PLATS VALUES (21,'Salmó-lluç al forn','',						15.0,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/21.jpeg'), 	FALSE,7);
INSERT INTO PLATS VALUES (22,'Arròs blanc','',								5.0,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/22.jpg'), 	TRUE, 8);
INSERT INTO PLATS VALUES (23,'Arròs mexicà','',								10.3,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/23.jpg'), 	TRUE, 8);
INSERT INTO PLATS VALUES (24,'Gelat de xocolata','',						5.0,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/24.jpg'), 	TRUE, 10);
INSERT INTO PLATS VALUES (25,'Gelat de maduixa','',							5.0,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/25.jpg'), 	TRUE, 10);
INSERT INTO PLATS VALUES (26,'Gelat de tè matcha','',						8.5,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/26.jpeg'), 	TRUE, 10);
INSERT INTO PLATS VALUES (27,'Gelat de llimona','',							5.0,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/27.jpg'), 	FALSE,10);
INSERT INTO PLATS VALUES (28,'Gelat de menta','',							7.0,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/28.jpg'), 	TRUE, 10);
INSERT INTO PLATS VALUES (29,'Gelat de raïm','',							8.0,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/29.jpg'), 	TRUE, 10);
INSERT INTO PLATS VALUES (30,'Gelat fregit','',								10.5,	LOAD_FILE('D:/Documents/DAM2/Projecte/mySQL/Imatges/30.jpg'), 	TRUE, 10);

-- Insertem les taules estàtiques Unitats i Ingredients, a les que fa referència Línies d'Escandall
INSERT INTO UNITATS VALUES (1,'Grams');
INSERT INTO UNITATS VALUES (2,'Quilograms');
INSERT INTO UNITATS VALUES (3,'Mil·ligrams');
INSERT INTO UNITATS VALUES (4,'Unces');
INSERT INTO UNITATS VALUES (5,'Peces');
INSERT INTO UNITATS VALUES (6,'Litres');
INSERT INTO UNITATS VALUES (7,'Mil·lilitres');

INSERT INTO INGREDIENTS VALUES (1,'Enciam');
INSERT INTO INGREDIENTS VALUES (2,'Arròs');
INSERT INTO INGREDIENTS VALUES (3,'Tomàquet');
INSERT INTO INGREDIENTS VALUES (4,'Mantega');
INSERT INTO INGREDIENTS VALUES (5,'Oli');
INSERT INTO INGREDIENTS VALUES (6,'Ceba');
INSERT INTO INGREDIENTS VALUES (7,'Pollastre');
INSERT INTO INGREDIENTS VALUES (8,'Porc');
INSERT INTO INGREDIENTS VALUES (9,'Julivert');
INSERT INTO INGREDIENTS VALUES (10,'All');
INSERT INTO INGREDIENTS VALUES (11,'Llenties');
INSERT INTO INGREDIENTS VALUES (12,'Pasta');
INSERT INTO INGREDIENTS VALUES (13,'Lluç');
INSERT INTO INGREDIENTS VALUES (14,'Salmó');
INSERT INTO INGREDIENTS VALUES (15,'Maduixes');
INSERT INTO INGREDIENTS VALUES (16,'Xocolata');
INSERT INTO INGREDIENTS VALUES (17,'Romaní');
INSERT INTO INGREDIENTS VALUES (18,'Sal');
INSERT INTO INGREDIENTS VALUES (19,'Sucre');
INSERT INTO INGREDIENTS VALUES (20,'Vi blanc');
INSERT INTO INGREDIENTS VALUES (21,'Vi negre');
INSERT INTO INGREDIENTS VALUES (22,'Llimona');
INSERT INTO INGREDIENTS VALUES (23,'Carbassó');
INSERT INTO INGREDIENTS VALUES (24,'Albergínia');
INSERT INTO INGREDIENTS VALUES (25,'Meló');
INSERT INTO INGREDIENTS VALUES (26,'Coliflor');
INSERT INTO INGREDIENTS VALUES (27,'Quinoa');
INSERT INTO INGREDIENTS VALUES (28,'Cigrons');
INSERT INTO INGREDIENTS VALUES (29,'Mongetes');
INSERT INTO INGREDIENTS VALUES (30,'Farina');
INSERT INTO INGREDIENTS VALUES (31,'Ou');
INSERT INTO INGREDIENTS VALUES (32,'Patata');
INSERT INTO INGREDIENTS VALUES (33,'Tè matcha');
INSERT INTO INGREDIENTS VALUES (34,'Pa');
INSERT INTO INGREDIENTS VALUES (35,'Tonyina');
INSERT INTO INGREDIENTS VALUES (36,'Formatge');
INSERT INTO INGREDIENTS VALUES (37,'Aigua');
INSERT INTO INGREDIENTS VALUES (38,'Nata');
INSERT INTO INGREDIENTS VALUES (39,'Curry');
INSERT INTO INGREDIENTS VALUES (40,'Pastanaga');
INSERT INTO INGREDIENTS VALUES (41,'Pèsols');
INSERT INTO INGREDIENTS VALUES (42,'Menta');
INSERT INTO INGREDIENTS VALUES (43,'Raïm');

-- Insertem línies d'escandall per als plats

INSERT INTO LINIES_ESCANDALL VALUES (1,1,10,7,4);
INSERT INTO LINIES_ESCANDALL VALUES (2,1,200,1,1);
INSERT INTO LINIES_ESCANDALL VALUES (3,1,1,34,5);
INSERT INTO LINIES_ESCANDALL VALUES (1,2,2,3,5);
INSERT INTO LINIES_ESCANDALL VALUES (2,2,400,23,1);
INSERT INTO LINIES_ESCANDALL VALUES (3,2,1,31,5);
INSERT INTO LINIES_ESCANDALL VALUES (1,3,3,31,5);
INSERT INTO LINIES_ESCANDALL VALUES (2,3,300,35,1);
INSERT INTO LINIES_ESCANDALL VALUES (1,4,250,2,7);
INSERT INTO LINIES_ESCANDALL VALUES (2,4,30,30,1);
INSERT INTO LINIES_ESCANDALL VALUES (3,4,30,9,3);
INSERT INTO LINIES_ESCANDALL VALUES (4,4,2,31,5);
INSERT INTO LINIES_ESCANDALL VALUES (1,5,250,12,1);
INSERT INTO LINIES_ESCANDALL VALUES (1,6,1,23,5);
INSERT INTO LINIES_ESCANDALL VALUES (1,7,100,36,1);
INSERT INTO LINIES_ESCANDALL VALUES (2,7,2,37,6);
INSERT INTO LINIES_ESCANDALL VALUES (3,7,10,7,4);
INSERT INTO LINIES_ESCANDALL VALUES (1,9,500,7,1);
INSERT INTO LINIES_ESCANDALL VALUES (2,9,430,38,7);
INSERT INTO LINIES_ESCANDALL VALUES (3,9,15,39,1);
INSERT INTO LINIES_ESCANDALL VALUES (1,10,1,14,5);
INSERT INTO LINIES_ESCANDALL VALUES (2,10,400,2,1);
INSERT INTO LINIES_ESCANDALL VALUES (1,11,300,12,1);
INSERT INTO LINIES_ESCANDALL VALUES (2,11,30,1,1);
INSERT INTO LINIES_ESCANDALL VALUES (3,11,2,3,5);
INSERT INTO LINIES_ESCANDALL VALUES (1,12,50,19,1);
INSERT INTO LINIES_ESCANDALL VALUES (2,12,2,22,5);
INSERT INTO LINIES_ESCANDALL VALUES (1,13,3,32,5);
INSERT INTO LINIES_ESCANDALL VALUES (2,13,1,40,5);
INSERT INTO LINIES_ESCANDALL VALUES (1,14,500,15,1);
INSERT INTO LINIES_ESCANDALL VALUES (1,15,300,8,1);
INSERT INTO LINIES_ESCANDALL VALUES (1,16,1,7,5);
INSERT INTO LINIES_ESCANDALL VALUES (2,16,2,32,2);
INSERT INTO LINIES_ESCANDALL VALUES (1,17,250,7,1);
INSERT INTO LINIES_ESCANDALL VALUES (2,17,500,37,7);
INSERT INTO LINIES_ESCANDALL VALUES (3,17,300,9,3);
INSERT INTO LINIES_ESCANDALL VALUES (1,18,1,8,5);
INSERT INTO LINIES_ESCANDALL VALUES (2,18,2,6,5);
INSERT INTO LINIES_ESCANDALL VALUES (1,19,3,14,5);
INSERT INTO LINIES_ESCANDALL VALUES (1,20,3,13,5);
INSERT INTO LINIES_ESCANDALL VALUES (1,21,1,14,5);
INSERT INTO LINIES_ESCANDALL VALUES (2,21,1,13,5);
INSERT INTO LINIES_ESCANDALL VALUES (3,21,2,32,2);
INSERT INTO LINIES_ESCANDALL VALUES (1,22,500,2,1);
INSERT INTO LINIES_ESCANDALL VALUES (1,23,300,2,1);
INSERT INTO LINIES_ESCANDALL VALUES (2,23,500,3,1);
INSERT INTO LINIES_ESCANDALL VALUES (3,23,300,41,1);
INSERT INTO LINIES_ESCANDALL VALUES (1,25,25,15,5);
INSERT INTO LINIES_ESCANDALL VALUES (1,26,240,33,3);
INSERT INTO LINIES_ESCANDALL VALUES (2,26,500,37,7);
INSERT INTO LINIES_ESCANDALL VALUES (1,27,5,22,5);
INSERT INTO LINIES_ESCANDALL VALUES (2,27,500,37,7);
INSERT INTO LINIES_ESCANDALL VALUES (1,28,100,42,1);
INSERT INTO LINIES_ESCANDALL VALUES (2,28,500,37,7);
INSERT INTO LINIES_ESCANDALL VALUES (1,29,1,43,2);
INSERT INTO LINIES_ESCANDALL VALUES (2,29,500,37,7);
INSERT INTO LINIES_ESCANDALL VALUES (1,30,500,38,7);
INSERT INTO LINIES_ESCANDALL VALUES (2,30,500,37,7);
INSERT INTO LINIES_ESCANDALL VALUES (3,30,500,30,3);

-- Insertem cambrers, que no referencien a ningú
-- Per ara guardem les contrassenyes com a string, però podríem guardar Hash

INSERT INTO CAMBRERS VALUES (1,'Bernat','Farrés',NULL,'befa','BeFa');
INSERT INTO CAMBRERS VALUES (2,'Ester','Comaposada','Marull','esco','EsCo');
INSERT INTO CAMBRERS VALUES (3,'Marc','Barnés',NULL,'maba','MaBa');
INSERT INTO CAMBRERS VALUES (4,'Amanda','Borràs','Belladonna','ambo','AmBo');
INSERT INTO CAMBRERS VALUES (5,'Isidre','Salisi','Senmenat','issa','IsSa');
INSERT INTO CAMBRERS VALUES (6,'Pere','Galindo',NULL,'pega','PeGa');
INSERT INTO CAMBRERS VALUES (7,'Rosa','Saragossa',NULL,'rosa','RoSa');

-- Insertem Taules i Comandes, que es referencien mútuament

INSERT INTO TAULES VALUES (1,NULL);
INSERT INTO TAULES VALUES (2,NULL);
INSERT INTO TAULES VALUES (3,NULL);
INSERT INTO TAULES VALUES (4,NULL);
INSERT INTO TAULES VALUES (5,NULL);
INSERT INTO TAULES VALUES (6,NULL);
INSERT INTO TAULES VALUES (7,NULL);

INSERT INTO COMANDES VALUES (1,'2021-05-21 21:00:00',2,2);
INSERT INTO COMANDES VALUES (2,'2021-05-21 21:01:00',3,3);
INSERT INTO COMANDES VALUES (3,'2021-05-21 21:02:00',5,1);
INSERT INTO COMANDES VALUES (4,'2021-05-21 21:03:00',1,6);
INSERT INTO COMANDES VALUES (5,'2021-05-21 21:10:00',7,4);
INSERT INTO COMANDES VALUES (6,'2021-05-21 21:06:00',4,7);

UPDATE TAULES SET COMANDA_ACTIVA=4 WHERE TAULA_ID=1;
UPDATE TAULES SET COMANDA_ACTIVA=1 WHERE TAULA_ID=2;
UPDATE TAULES SET COMANDA_ACTIVA=2 WHERE TAULA_ID=3;
UPDATE TAULES SET COMANDA_ACTIVA=3 WHERE TAULA_ID=5;
UPDATE TAULES SET COMANDA_ACTIVA=5 WHERE TAULA_ID=7;
UPDATE TAULES SET COMANDA_ACTIVA=6 WHERE TAULA_ID=4;

-- Per últim, insertem Línies de comanda que referencien a comandes

INSERT INTO LINIES_COMANDA VALUES (1,1,1,1	,'EN_PREPARACIO');
INSERT INTO LINIES_COMANDA VALUES (2,1,5,3	,'EN_PREPARACIO');
INSERT INTO LINIES_COMANDA VALUES (1,2,22,5	,'PREPARADA');
INSERT INTO LINIES_COMANDA VALUES (2,2,25,2	,'EN_PREPARACIO');
INSERT INTO LINIES_COMANDA VALUES (3,2,15,1	,'PREPARADA');
INSERT INTO LINIES_COMANDA VALUES (1,3,10,2	,'PREPARADA');
INSERT INTO LINIES_COMANDA VALUES (2,3,15,5	,'PREPARADA');
INSERT INTO LINIES_COMANDA VALUES (1,4,5,10	,'EN_PREPARACIO');
INSERT INTO LINIES_COMANDA VALUES (2,4,1,1	,'EN_PREPARACIO');
INSERT INTO LINIES_COMANDA VALUES (3,4,30,3	,'EN_PREPARACIO');
INSERT INTO LINIES_COMANDA VALUES (4,4,26,2	,'EN_PREPARACIO');
INSERT INTO LINIES_COMANDA VALUES (1,5,11,1	,'EN_PREPARACIO');
INSERT INTO LINIES_COMANDA VALUES (2,5,12,1	,'EN_PREPARACIO');
INSERT INTO LINIES_COMANDA VALUES (3,5,19,3	,'PREPARADA');
INSERT INTO LINIES_COMANDA VALUES (4,5,3,2	,'PREPARADA');
INSERT INTO LINIES_COMANDA VALUES (5,5,8,2	,'EN_PREPARACIO');
INSERT INTO LINIES_COMANDA VALUES (1,6,16,2	,'PREPARADA');
INSERT INTO LINIES_COMANDA VALUES (2,6,5,2	,'EN_PREPARACIO');