-- Creació de l'esquema, per si encara no el tenim o l'hem esborrat
CREATE SCHEMA COOK_O_MATIC_BD;

-- Primer creem les taules d'informació al voltant del plat
-- Creem primer les tres taules amb dades estàtiques, que no tenen claus foranes
CREATE TABLE CATEGORIES (
	CATEGORIA_ID 		SMALLINT (3) CHECK ( CATEGORIA_ID >= 0 AND CATEGORIA_ID < 999),
	NOM     			VARCHAR(25) NOT NULL ,
	COLOR				VARCHAR(6),

	PRIMARY KEY(CATEGORIA_ID)
);

CREATE TABLE INGREDIENTS (
	INGREDIENT_ID 		SMALLINT (3) CHECK ( INGREDIENT_ID >= 0 AND INGREDIENT_ID < 999),
	NOM     			VARCHAR(25) NOT NULL ,

	PRIMARY KEY(INGREDIENT_ID)
);

CREATE TABLE UNITATS (
	UNITAT_ID 			SMALLINT (3) CHECK ( UNITAT_ID >= 0 AND UNITAT_ID < 999),
	NOM     			VARCHAR(25) NOT NULL ,

	PRIMARY KEY(UNITAT_ID)
);

-- Creem la taula de plats, que només referencia "CATEGORIES"
CREATE TABLE PLATS (
	PLAT_ID   		SMALLINT(5) 	CHECK ( PLAT_ID >= 0 AND PLAT_ID < 9999),              
	NOM				VARCHAR(50)		NOT NULL,
	DESCRIPCIO_MD 	TEXT,
	PREU   			DECIMAL(15,2),
	FOTO			MEDIUMBLOB,
	DISPONIBLE		BOOLEAN			NOT NULL,
	CATEGORIA		SMALLINT(3),
	
	PRIMARY KEY (PLAT_ID),
	CONSTRAINT `PLATS_FK_CATEGORIA` FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIES (CATEGORIA_ID)  ON DELETE SET NULL
);

-- Creem la taula de línies de l'escandall, que referencia "PLATS", "INGREDIENTS" i "UNITATS"
CREATE TABLE LINIES_ESCANDALL (
	LINIA_ESC_ID   	MEDIUMINT(7) 	CHECK ( LINIA_ESC_ID >= 0 AND LINIA_ESC_ID < 9999999),   
	PLAT			SMALLINT(5)		NOT NULL,
	QUANTITAT		MEDIUMINT(7),
	INGREDIENT		SMALLINT(3)		NOT NULL,
	UNITAT			SMALLINT(3)		NOT NULL,	
	
	PRIMARY KEY (PLAT,LINIA_ESC_ID),
	CONSTRAINT `LINIES_ESCANDALL_FK_PLATS` FOREIGN KEY (PLAT) REFERENCES PLATS (PLAT_ID) ON DELETE CASCADE,
	CONSTRAINT `LINIES_ESCANDALL_FK_INGREDIENTS` FOREIGN KEY (INGREDIENT) REFERENCES INGREDIENTS (INGREDIENT_ID) ON DELETE CASCADE,
	CONSTRAINT `LINIES_ESCANDALL_FK_UNITATS` FOREIGN KEY (UNITAT) REFERENCES UNITATS (UNITAT_ID) ON DELETE CASCADE
);

-- Finalment, creem les taules referents a les comandes
-- 


-- CREATE TABLE CIRCUITS (

-- COD            INTEGER(2)  CHECK   ( COD > 0 AND  COD < 30 ),                              
-- GRAND_PRIX       VARCHAR(40)  NOT NULL,
-- COUNTRY_CIRCUIT      CHAR(3)  NOT NULL ,                          
-- NAME_CIRCUIT   VARCHAR(40)  NOT NULL,
  -- TOWN        VARCHAR(25)  NOT NULL,
-- LAPS           INTEGER(3)  NOT NULL  CHECK  (LAPS > 0 AND LAPS < 90 ),
        -- PRIMARY KEY (COD),      
        -- CONSTRAINT `CIRCUITS_FK_COUNTRY_COD` FOREIGN KEY (COUNTRY_CIRCUIT) REFERENCES COUNTRIES (COD_COUNTRY)  ON UPDATE CASCADE
       
-- );

-- CREATE TABLE STANDINGS (

-- RACE_NUM      INTEGER(2) ,
-- POSITION  INTEGER(2)   CHECK ( POSITION > 0 AND POSITION < 22 ),          
-- NO_DRIVER      INTEGER (2)  NOT NULL,                      
-- TEAM           INTEGER(2)  NOT NULL,
-- LAPS          INTEGER(3) CHECK ( LAPS >=  0 AND LAPS <= 90 ),
-- DATE_RACE		DATE NOT NULL,
-- HOURS         INTEGER(2)    NOT NULL,
-- MINUTES        INTEGER(2)    NOT NULL,
-- SECONDS        INTEGER(2)    NOT NULL,
-- POINTS        INTEGER(2)  CHECK ( POINTS >=  0 AND POINTS <= 25 ),
-- CIRCUIT           INTEGER(2)  NOT NULL,
-- CLOSED			INTEGER (1) NOT NULL,
   
-- PRIMARY KEY (RACE_NUM,POSITION),
-- CONSTRAINT `STANDINGS_FK_NO_DRIVER_NUM_DRIVER` FOREIGN KEY (NO_DRIVER) REFERENCES DRIVERS (NUM_DRIVER) ON UPDATE CASCADE,
-- CONSTRAINT `STANDINGS_FK_TEAMS_TEAM_COD` FOREIGN KEY (TEAM) REFERENCES TEAMS (TEAM_COD)  ON UPDATE CASCADE,
-- CONSTRAINT `STANDINGS_FK_CIRCUIT_CIRCUIT` FOREIGN KEY (CIRCUIT) REFERENCES CIRCUITS (COD)  ON UPDATE CASCADE       
           
-- );