-- Creació de l'esquema, per si encara no el tenim o l'hem esborrat
CREATE SCHEMA COOK_O_MATIC_BD;

-- Creem primer les tres taules amb dades estàtiques, que no tenen claus foranes

CREATE TABLE CATEGORIES (
	ID 		INTEGER (3),
	NOM     VARCHAR(25) NOT NULL ,
	COLOR	VARCHAR(6),

PRIMARY KEY(ID)
);

CREATE TABLE PLATS (
	ID   			INTEGER(3) 		CHECK ( TEAM_COD >= 0 AND TEAM_COD < 999),              
	NOM				VARCHAR(50)		NOT NULL,
	DESCRIPCIO_MD 	TEXT,
	PREU   			DECIMAL(15,2),
	
	-- CHASSIS       VARCHAR(38)  NOT NULL,
	-- POWER_UNIT   VARCHAR(38)  NOT NULL,
	-- FIRST_TEAM_ENTRY integer(4) ,
	-- WORLD_CHAMPIONSHIPS INTEGER(3) CHECK(WORLD_CHAMPIONSHIPS > 0 OR WORLD_CHAMPIONSHIPS < 100 ),
	-- FASTEST_LAPS INTEGER(3) CHECK(FASTEST_LAPS > 0 OR FASTEST_LAPS < 100 ),                   
	-- DESCR   VARCHAR(1200),
	-- POINTS INTEGER(3) CHECK(POINTS >= 0),
	-- MAIN_COLOUR INTEGER(255) NULL,
	-- LOGO VARCHAR(50),
	-- CAR VARCHAR(50),
	
	-- PRIMARY KEY (TEAM_COD)
);

-- CREATE TABLE CIRCUITS (

-- COD            INTEGER(2)  CHECK   ( COD > 0 AND  COD < 30 ),                              
-- GRAND_PRIX       VARCHAR(40)  NOT NULL,
-- COUNTRY_CIRCUIT      CHAR(3)  NOT NULL ,                          
-- NAME_CIRCUIT   VARCHAR(40)  NOT NULL,
  -- TOWN        VARCHAR(25)  NOT NULL,
-- LAPS           INTEGER(3)  NOT NULL  CHECK  (LAPS > 0 AND LAPS < 90 ),
        -- PRIMARY KEY (COD),      
        -- CONSTRAINT `CIRCUITS_FK_COUNTRY_COD` FOREIGN KEY (COUNTRY_CIRCUIT) REFERENCES COUNTRIES (COD_COUNTRY)  ON UPDATE CASCADE
       
-- );

-- CREATE TABLE STANDINGS (

-- RACE_NUM      INTEGER(2) ,
-- POSITION  INTEGER(2)   CHECK ( POSITION > 0 AND POSITION < 22 ),          
-- NO_DRIVER      INTEGER (2)  NOT NULL,                      
-- TEAM           INTEGER(2)  NOT NULL,
-- LAPS          INTEGER(3) CHECK ( LAPS >=  0 AND LAPS <= 90 ),
-- DATE_RACE		DATE NOT NULL,
-- HOURS         INTEGER(2)    NOT NULL,
-- MINUTES        INTEGER(2)    NOT NULL,
-- SECONDS        INTEGER(2)    NOT NULL,
-- POINTS        INTEGER(2)  CHECK ( POINTS >=  0 AND POINTS <= 25 ),
-- CIRCUIT           INTEGER(2)  NOT NULL,
-- CLOSED			INTEGER (1) NOT NULL,
   
-- PRIMARY KEY (RACE_NUM,POSITION),
-- CONSTRAINT `STANDINGS_FK_NO_DRIVER_NUM_DRIVER` FOREIGN KEY (NO_DRIVER) REFERENCES DRIVERS (NUM_DRIVER) ON UPDATE CASCADE,
-- CONSTRAINT `STANDINGS_FK_TEAMS_TEAM_COD` FOREIGN KEY (TEAM) REFERENCES TEAMS (TEAM_COD)  ON UPDATE CASCADE,
-- CONSTRAINT `STANDINGS_FK_CIRCUIT_CIRCUIT` FOREIGN KEY (CIRCUIT) REFERENCES CIRCUITS (COD)  ON UPDATE CASCADE       
           
-- );